# Generated by Django 3.2.2 on 2022-03-07 19:19

from django.db import migrations, models
import django.db.models.deletion


def CreateDefaultFolder(apps, schema_editor):
    Folder = apps.get_model("api", "Folder")

    # make default folder if not exists
    Folder.objects.update_or_create(name='Unsorted')


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filename', models.TextField()),
                ('hash', models.TextField(null=True)),
                ('temp_path', models.TextField(null=True)),
                ('filestore_path', models.TextField(null=True)),
                ('status', models.TextField(
                    choices=[('CREATED', 'CREATED'), ('PERSISTING', 'PERSISTING'), ('PERSISTED', 'PERSISTED'),
                             ('TRANSLATING_PDF_TO_IMAGES', 'TRANSLATING_PDF_TO_IMAGES'),
                             ('TRANSLATED_PDF_TO_IMAGES', 'TRANSLATED_PDF_TO_IMAGES'), ('ANNOTATING', 'ANNOTATING'),
                             ('ANNOTATED', 'ANNOTATED')], default='CREATED')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gc_api_key', models.TextField()),
                ('nfs_path', models.TextField()),
                ('secret_key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('temp_path', models.TextField(null=True)),
                ('text', models.TextField(null=True)),
                ('metadata', models.TextField(null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages',
                                               to='api.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.TextField(
                    choices=[('PERSIST', 'PERSIST'), ('TRANSLATE_TO_IMAGES', 'TRANSLATE_TO_IMAGES'),
                             ('ANNOTATE', 'ANNOTATE')])),
                ('current_status', models.TextField(
                    choices=[('CREATED', 'CREATED'), ('PERSISTING', 'PERSISTING'), ('PERSISTED', 'PERSISTED'),
                             ('TRANSLATING_PDF_TO_IMAGES', 'TRANSLATING_PDF_TO_IMAGES'),
                             ('TRANSLATED_PDF_TO_IMAGES', 'TRANSLATED_PDF_TO_IMAGES'), ('ANNOTATING', 'ANNOTATING'),
                             ('ANNOTATED', 'ANNOTATED')])),
                ('desired_status', models.TextField(
                    choices=[('CREATED', 'CREATED'), ('PERSISTING', 'PERSISTING'), ('PERSISTED', 'PERSISTED'),
                             ('TRANSLATING_PDF_TO_IMAGES', 'TRANSLATING_PDF_TO_IMAGES'),
                             ('TRANSLATED_PDF_TO_IMAGES', 'TRANSLATED_PDF_TO_IMAGES'), ('ANNOTATING', 'ANNOTATING'),
                             ('ANNOTATED', 'ANNOTATED')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('successful', models.BooleanField(null=True)),
                ('failed_reason', models.TextField(null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents',
                                    to='api.folder'),
        ),
        migrations.RunPython(CreateDefaultFolder),
    ]
