# Generated by Django 3.2.2 on 2021-05-08 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('hash', models.TextField(null=True)),
                ('temp_path', models.TextField(null=True)),
                ('filestore_path', models.TextField(null=True)),
                ('status', models.TextField(choices=[('CREATED', 'CREATED'), ('PERSISTING', 'PERSISTING'), ('PERSISTED', 'PERSISTED'), ('TRANSLATING_PDF_TO_IMAGES', 'TRANSLATING_PDF_TO_IMAGES'), ('TRANSLATED_PDF_TO_IMAGES', 'TRANSLATED_PDF_TO_IMAGES'), ('ANNOTATING', 'ANNOTATING'), ('ANNOTATED', 'ANNOTATED')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('temp_path', models.TextField(null=True)),
                ('text', models.TextField(null=True)),
                ('metadata', models.TextField(null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.TextField(choices=[('PERSIST', 'PERSIST'), ('TRANSLATE_TO_IMAGES', 'TRANSLATE_TO_IMAGES'), ('ANNOTATE', 'ANNOTATE')])),
                ('current_status', models.TextField(choices=[('CREATED', 'CREATED'), ('PERSISTING', 'PERSISTING'), ('PERSISTED', 'PERSISTED'), ('TRANSLATING_PDF_TO_IMAGES', 'TRANSLATING_PDF_TO_IMAGES'), ('TRANSLATED_PDF_TO_IMAGES', 'TRANSLATED_PDF_TO_IMAGES'), ('ANNOTATING', 'ANNOTATING'), ('ANNOTATED', 'ANNOTATED')])),
                ('desired_status', models.TextField(choices=[('CREATED', 'CREATED'), ('PERSISTING', 'PERSISTING'), ('PERSISTED', 'PERSISTED'), ('TRANSLATING_PDF_TO_IMAGES', 'TRANSLATING_PDF_TO_IMAGES'), ('TRANSLATED_PDF_TO_IMAGES', 'TRANSLATED_PDF_TO_IMAGES'), ('ANNOTATING', 'ANNOTATING'), ('ANNOTATED', 'ANNOTATED')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('successful', models.BooleanField(null=True)),
                ('failed_reason', models.TextField(null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.document')),
            ],
        ),
    ]
