# Generated by Django 3.2.12 on 2022-03-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source_content_type',
            field=models.IntegerField(choices=[(1, 'Jpeg'), (2, 'Png'), (3, 'Pdf')], default=3),
        ),
    ]
