# Generated by Django 3.2.2 on 2021-06-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField()),
                ('nfs_path', models.TextField()),
                ('secret_key', models.TextField()),
            ],
        ),
    ]
