# Generated by Django 3.2.2 on 2021-07-08 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_setup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setup',
            old_name='api_key',
            new_name='gc_api_key',
        ),
    ]
