# Generated by Django 3.2.12 on 2022-04-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentjob',
            old_name='job',
            new_name='kind',
        ),
    ]
