# Generated by Django 3.2.2 on 2021-07-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_api_key_setup_gc_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.TextField(choices=[('CREATED', 'CREATED'), ('PERSISTING', 'PERSISTING'), ('PERSISTED', 'PERSISTED'), ('TRANSLATING_PDF_TO_IMAGES', 'TRANSLATING_PDF_TO_IMAGES'), ('TRANSLATED_PDF_TO_IMAGES', 'TRANSLATED_PDF_TO_IMAGES'), ('ANNOTATING', 'ANNOTATING'), ('ANNOTATED', 'ANNOTATED')], default='CREATED'),
        ),
    ]
