# Generated by Django 3.2.15 on 2022-08-21 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0004_rename_job_documentjob_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageSettingsLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_path', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageSettingsNFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_path', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageSettingsS3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_access_key_id', models.TextField()),
                ('aws_secret_access_key', models.TextField()),
                ('bucket', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='settings',
            name='storage_path',
        ),
        migrations.AddField(
            model_name='settings',
            name='storage_settings_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='storage_settings_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='storage_mode',
            field=models.CharField(choices=[('local', 'Local'), ('nfs', 'Nfs'), ('s3', 'S3')], default='local', max_length=20),
        ),
        migrations.AddIndex(
            model_name='settings',
            index=models.Index(fields=['storage_settings_type', 'storage_settings_id'], name='api_setting_storage_6d74f7_idx'),
        ),
    ]
